title: "Julie Perreau"
description: "Graduate student at the University of Texas at Austin"
show_downloads: true
google_analytics: G-KKQ46BRWC9
permalink: /:categories/:year-:month-:day-:title.html
pages_list:
  Home: '/index'
  CV and Publications: '/cv'
plugins:
  - jekyll-feed
 github: [metadata]
