theme: jekyll-theme-minimal
title: Julie Perreau
description: Graduate student, University of Texas at Austin
show_downloads: true
google_analytics: G-KKQ46BRWC9
permalink: /:categories/:year-:month-:day-:title.html
pages_list:
  Home: '/index'
  Research: '/research'
  CV and Publications: '/cv_pubs'
plugins:
  - jekyll-feed
 github: [metadata]
  
  
